version: 2.1
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test