version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: set environment variables
          command: echo 'export BUILD_NUMBER=$CIRCLE_BUILD_NUM' >> $BASH_ENV
      - run:
          name: install npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install packages
          command: npm install
      - run:
          name: run unit tests, lint project
          command: npm run ci
      - run:
          name: build project
          command: npm run build
      - run:
          name: set git email
          command: git config user.email "contact.oliver.wilson@gmail.com"
      - run:
          name: set git name
          command: git config user.name "Circle CI Oliver Wilson"
      - run:
          name: Git add all files
          command: git add -A
      - run:
          name: add build files and commit
          command: git commit -a -m "Build no $CIRCLE_BUILD_NUM $CIRCLE_BUILD_URL"
      - run:
          name: git push
          command: git push origin develop:master --force

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
