version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install packages
          command: npm install
      - run:
          name: run unit tests
          command: npm run ci
      - run:
          name: build proejct
          command: npm run build
      - run:
          name: set git email
          command: git config user.email "contact.oliver.wilson@gmail.com"
      - run:
          name: set git name
          command: git config user.name "Circle CI Oliver Wilson"
      - run:
          name: add build files and commit
          command: git commit -a -m "$CIRCLE_BRANCH"
      - run:
          name: git push
          command: git push origin master

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
