# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release Application to the Google Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: clean install all dependencies
      run: npm install
    - name: build the application
      run: npm run build
  
  setup_gcloud_cli:
    runs-on: ubuntu-latest
    steps:
    - name: setup google cloud platform cli
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build, setup_gcloud_cli]
    steps:
    - name: deploy app to google cloud
      run: gcloud app deploy --stop-previous-version
